services:
#################################################################
  hoarder:
    container_name: hoarder
    image: ghcr.io/hoarder-app/hoarder:${HOARDER_VERSION:-release}
    volumes:
      - ./data/hoarder:/data
    env_file:
      - .env
    environment:
      MEILI_ADDR: http://meilisearch:7700
      BROWSER_WEB_URL: http://chrome:9222
      DATA_DIR: /data
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      proxy:
      default:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.hoarder.entrypoints=http"
      - "traefik.http.routers.hoarder.rule=Host(`hoarder.local.willkimble.net`)"
      - "traefik.http.middlewares.hoarder-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.hoarder.middlewares=hoarder-https-redirect"
      - "traefik.http.routers.hoarder-secure.entrypoints=https"
      - "traefik.http.routers.hoarder-secure.rule=Host(`hoarder.local.willkimble.net`)"
      - "traefik.http.routers.hoarder-secure.tls=true"
      - "traefik.http.routers.hoarder-secure.service=hoarder"
      - "traefik.http.services.hoarder.loadbalancer.server.port=3000"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.hoarder-secure-middlewares=authelia@docker"
      - "com.centurylinklabs.watchtower.enable=true"
#################################################################
  chrome:
    container_name: hoarder-chrome
    image: gcr.io/zenika-hub/alpine-chrome:123
    restart: unless-stopped
    command:
      - --no-sandbox
      - --disable-gpu
      - --disable-dev-shm-usage
      - --remote-debugging-address=0.0.0.0
      - --remote-debugging-port=9222
      - --hide-scrollbars
#################################################################
  meilisearch:
    container_name: hoarder-meilisearch
    image: getmeili/meilisearch:v1.11.1
    restart: unless-stopped
    env_file:
      - .env
    environment:
      MEILI_NO_ANALYTICS: "true"
    volumes:
      - ./data/meilisearch/:/meili_data
#################################################################
networks:
  default:
  proxy:
    external: true
