services:
#################################################################
  wallos:
    container_name: wallos
    image: bellamy/wallos:latest
    #ports:
    #  - "8282:80/tcp"
    environment:
      TZ: 'America/Chicago'
    # Volumes store your data between container upgrades
    volumes:
      - ./data/db:/var/www/html/db
      - ./data/logos:/var/www/html/images/uploads/logos
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      proxy:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.wallos.entrypoints=http"
      - "traefik.http.routers.wallos.rule=Host(`wallos.local.willkimble.net`)"
      - "traefik.http.middlewares.wallos-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.wallos.middlewares=wallos-https-redirect"
      - "traefik.http.routers.wallos-secure.entrypoints=https"
      - "traefik.http.routers.wallos-secure.rule=Host(`wallos.local.willkimble.net`)"
      - "traefik.http.routers.wallos-secure.tls=true"
      - "traefik.http.routers.wallos-secure.service=wallos"
      - "traefik.http.services.wallos.loadbalancer.server.port=80"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.wallos-secure.middlewares=authelia@docker"
      - "com.centurylinklabs.watchtower.enable=true"
#################################################################
networks:
  proxy:
    external: true
