services:
#################################################################
  joplin_db:
    image: postgres:15
    container_name: joplin_db
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    expose:
      - 5432
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DATABASE}
    env_file:
      - .env
#################################################################
  joplin_server:
    image: joplin/server:latest
    container_name: joplin_server
    depends_on:
      - joplin_db
    expose:
      - 22300
    environment:
      - APP_PORT=22300
      - APP_BASE_URL=${APP_BASE_URL}
      - DB_CLIENT=pg
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DATABASE=${POSTGRES_DATABASE}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_HOST=joplin_db
      - STORAGE_DRIVER=Type=Filesystem; Path=/notes
      - STORAGE_DRIVER_FALLBACK=Type=Database; Mode=ReadAndWrite
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - /mnt/synology-nas/Files/personal/documents/Joplin:/notes
    security_opt:
      - no-new-privileges:true
    networks:
      - proxy
      - default
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.joplin.entrypoints=http"
      - "traefik.http.routers.joplin.rule=Host(`joplin.local.willkimble.net`)"
      - "traefik.http.middlewares.joplin-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.joplin.middlewares=joplin-https-redirect"
      - "traefik.http.routers.joplin-secure.entrypoints=https"
      - "traefik.http.routers.joplin-secure.rule=Host(`joplin.local.willkimble.net`)"
      - "traefik.http.routers.joplin-secure.tls=true"
      - "traefik.http.routers.joplin-secure.service=joplin"
      - "traefik.http.services.joplin.loadbalancer.server.port=22300"
      - "traefik.docker.network=proxy"
      - "com.centurylinklabs.watchtower.enable=true"
#################################################################
networks:
  default:
  proxy:
    external: true

