services:
#################################################################
  pinchflat:
    container_name: pinchflat
    user: 99:100 # should be owner of volumes
    image: ghcr.io/kieraneglin/pinchflat:latest
    environment:
      - PUID=99
      - PGID=100
      - TZ=Etc/UTC
    ports:
      - '8945:8945'
    volumes:
      - ./data/config:/config
      - /mnt/unraid-nas/data/media/youtube/Unsorted:/downloads
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      proxy:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pinchflat.entrypoints=http"
      - "traefik.http.routers.pinchflat.rule=Host(`pinchflat.local.willkimble.net`)"
      - "traefik.http.middlewares.pinchflat-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.pinchflat.middlewares=pinchflat-https-redirect"
      - "traefik.http.routers.pinchflat-secure.entrypoints=https"
      - "traefik.http.routers.pinchflat-secure.rule=Host(`pinchflat.local.willkimble.net`)"
      - "traefik.http.routers.pinchflat-secure.tls=true"
      - "traefik.http.routers.pinchflat-secure.service=pinchflat"
      - "traefik.http.services.pinchflat.loadbalancer.server.port=8945"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.pinchflat-secure-middlewares=authelia@docker"
      - "com.centurylinklabs.watchtower.enable=true"
#################################################################
networks:
  proxy:
    external: true
