services:
#################################################################
  gameyfin:
    image: grimsi/gameyfin:1.4.4
    container_name: gameyfin
    environment:
      - GAMEYFIN_USER=${GAMEYFIN_USER}
      - GAMEYFIN_PASSWORD=${GAMEYFIN_PASSWORD}
      - GAMEYFIN_IGDB_API_CLIENT_ID=${GAMEYFIN_IGDB_API_CLIENT_ID}
      - GAMEYFIN_IGDB_API_CLIENT_SECRET=${GAMEYFIN_IGDB_API_CLIENT_SECRET}
      - GAMEYFIN_SOURCES=/opt/gameyfin-library/library-1,/opt/gameyfin-library/library-2,/opt/gameyfin-library/library-3
    volumes:
      - /mnt/synology-nas/Files/data/media/games/pc:/opt/gameyfin-library/library-1
      - /mnt/synology-nas/Files/data/media/games/switch:/opt/gameyfin-library/library-2
      - /mnt/synology-nas/Files/data/media/games/vr:/opt/gameyfin-library/library-3
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      proxy:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gameyfin.entrypoints=http"
      - "traefik.http.routers.gameyfin.rule=Host(`gameyfin.local.willkimble.net`)"
      - "traefik.http.middlewares.gameyfin-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.gameyfin.middlewares=gameyfin-https-redirect"
      - "traefik.http.routers.gameyfin-secure.entrypoints=https"
      - "traefik.http.routers.gameyfin-secure.rule=Host(`gameyfin.local.willkimble.net`)"
      - "traefik.http.routers.gameyfin-secure.tls=true"
      - "traefik.http.routers.gameyfin-secure.service=gameyfin"
      - "traefik.http.services.gameyfin.loadbalancer.server.port=8080"
      - "traefik.docker.network=proxy"
      - "com.centurylinklabs.watchtower.enable=true"
      - "traefik.http.routers.gameyfin-secure.middlewares=authelia@docker"
#################################################################
networks:
  proxy:
    external: true
