services:
#################################################################
  adventurelog:
    #build: ./frontend/
    image: ghcr.io/seanmorley15/adventurelog-frontend:latest
    container_name: adventurelog
    environment:
      - PUBLIC_SERVER_URL=http://adventurelog-backend:8000 # MOST DOCKER USERS WILL NEVER NEED TO CHANGE THIS, EVEN IF YOU CHANGE THE PORTS
      - ORIGIN=https://adventurelog.local.willkimble.net
      - BODY_SIZE_LIMIT=Infinity # This is measured in bytes
    expose:
      - "3000"
    depends_on:
      - adventurelog-backend
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      proxy:
      default:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.adventurelog.entrypoints=http"
      - "traefik.http.routers.adventurelog.rule=Host(`adventurelog.local.willkimble.net`) && !PathPrefix(`/media`)"
      - "traefik.http.middlewares.adventurelog-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.adventurelog.middlewares=adventurelog-https-redirect"
      - "traefik.http.routers.adventurelog-secure.entrypoints=https"
      - "traefik.http.routers.adventurelog-secure.rule=Host(`adventurelog.local.willkimble.net`) && !PathPrefix(`/media`)"
      - "traefik.http.routers.adventurelog-secure.tls=true"
      - "traefik.http.routers.adventurelog-secure.service=adventurelog"
      - "traefik.http.services.adventurelog.loadbalancer.server.port=3000"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.adventurelog-secure-middlewares=authelia@docker"
      - "com.centurylinklabs.watchtower.enable=true"
#################################################################
  adventurelog-db:
    image: postgis/postgis:15-3.3
    container_name: adventurelog-db
    environment:
      POSTGRES_DB: database
      POSTGRES_USER: adventure
      POSTGRES_PASSWORD: nakdxajsdLm3VaP5brf2hRa7c47P6g
    volumes:
      - ./data/postgres:/var/lib/postgresql/data/
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
#################################################################
  adventurelog-backend:
    #build: ./backend/
    image: ghcr.io/seanmorley15/adventurelog-backend:latest
    container_name: adventurelog-backend
    environment:
      - PGHOST=adventurelog-db
      - PGDATABASE=database
      - PGUSER=adventure
      - PGPASSWORD=nakdxajsdLm3VaP5brf2hRa7c47P6g
      - SECRET_KEY=Q5vXKgspXp6oN6kshRP3q3bhvmUeTQ
      - DJANGO_ADMIN_USERNAME=admin
      - DJANGO_ADMIN_PASSWORD=admin
      - DJANGO_ADMIN_EMAIL=admin@example.com
      - PUBLIC_URL='http://localhost:80'
      - CSRF_TRUSTED_ORIGINS='https://adventurelog.local.willkimble.net'
      - DEBUG=False
      - FRONTEND_URL='https://adventurelog.local.willkimble.net'
    expose:
      - "8000"
    depends_on:
      - adventurelog-db
    volumes:
      - ./data/media:/code/media/
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
#################################################################
  adventurelog-nginx:
    image: nginx:latest
    container_name: adventurelog-nginx
    expose:
      - "80"
    volumes:
      - ./data/media:/app/media
      - ./data/proxy/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - adventurelog-backend
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
#################################################################
networks:
  default:
  proxy:
    external: true
