services:
#################################################################
  bookstack:
    image: lscr.io/linuxserver/bookstack:latest
    container_name: bookstack
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - APP_URL=${APP_URL}
      - APP_KEY=${APP_KEY}
      - DB_HOST=mariadb
      - DB_PORT=${DB_PORT}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DATABASE=${DB_DATABASE}
    env_file:
      - .env
    volumes:
      - ./data/bookstack/config:/config
    #ports:
    #  - 6875:80
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      proxy:
      default:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.bookstack.entrypoints=http"
      - "traefik.http.routers.bookstack.rule=Host(`bookstack.local.willkimble.net`)"
      - "traefik.http.middlewares.bookstack-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.bookstack.middlewares=bookstack-https-redirect"
      - "traefik.http.routers.bookstack-secure.entrypoints=https"
      - "traefik.http.routers.bookstack-secure.rule=Host(`bookstack.local.willkimble.net`)"
      - "traefik.http.routers.bookstack-secure.tls=true"
      - "traefik.http.routers.bookstack-secure.service=bookstack"
      - "traefik.http.services.bookstack.loadbalancer.server.port=80"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.bookstack-secure-middlewares=authelia@docker"
      - "com.centurylinklabs.watchtower.enable=true"
#################################################################
  mariadb:
    image: lscr.io/linuxserver/mariadb:latest
    container_name: bookstack-db
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    env_file:
      - .env
    volumes:
      - ./data/mariadb/config:/config
    expose:
      - 3306
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
#################################################################
networks:
  default:
  proxy:
    external: true
