services:
#################################################################
  speedtest:
    image: lscr.io/linuxserver/speedtest-tracker:latest
    container_name: speedtest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - APP_KEY=base64:beaJoAbtC5Zsm5iYlsYDFMVOhWEjYa2fy4Ab2eam3EU=
      - DB_CONNECTION=sqlite
      - SPEEDTEST_SCHEDULE="0 */6 * * *"
      - SPEEDTEST_SERVERS=8864,64151,35180
    volumes:
      - ./data:/config
    networks:
      proxy:
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.speedtest.entrypoints=http"
      - "traefik.http.routers.speedtest.rule=Host(`speedtest.local.willkimble.net`)"
      - "traefik.http.middlewares.speedtest-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.speedtest.middlewares=speedtest-https-redirect"
      - "traefik.http.routers.speedtest-secure.entrypoints=https"
      - "traefik.http.routers.speedtest-secure.rule=Host(`speedtest.local.willkimble.net`)"
      - "traefik.http.routers.speedtest-secure.tls=true"
      - "traefik.http.routers.speedtest-secure.service=speedtest"
      - "traefik.http.services.speedtest.loadbalancer.server.port=80"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.speedtest-secure-middlewares=authelia@docker"
#################################################################
networks:
  proxy:
    external: true
