version: '3.3'
services:
#################################################################
  speedtest:
    image: lscr.io/linuxserver/speedtest-tracker:latest
    container_name: speedtest
    expose:
      - 443
    environment:
      - PUID=1000
      - PGID=1000
      - DB_CONNECTION=pgsql
      - DB_HOST=speedtest_db
      - DB_PORT=5432
      - DB_DATABASE=speedtest_tracker
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
    env_file:
      - .env
    volumes:
      - ./data/config:/config
      - ./data/web:/etc/ssl/web
    depends_on:
      - db
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      proxy:
      default:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.speedtest.entrypoints=http"
      - "traefik.http.routers.speedtest.rule=Host(`speedtest.local.willkimble.net`)"
      - "traefik.http.middlewares.speedtest-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.speedtest.middlewares=gameyfin-https-redirect"
      - "traefik.http.routers.speedtest-secure.entrypoints=https"
      - "traefik.http.routers.speedtest-secure.rule=Host(`speedtest.local.willkimble.net`)"
      - "traefik.http.routers.speedtest-secure.tls=true"
      - "traefik.http.routers.speedtest-secure.service=speedtest"
      - "traefik.http.services.speedtest.loadbalancer.server.port=80"
      - "traefik.docker.network=proxy"
#################################################################
  db:
    image: postgres:15
    container_name: speedtest_db
    restart: unless-stopped
    env_file:
      - .env
    networks:
      default:
    environment:
      - POSTGRES_DB=speedtest_tracker
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./data/postgres/data:/var/lib/postgresql/data
#################################################################
networks:
  default:
  proxy:
    external: true
