version: "3.3"
services:
#################################################################
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    ports:
      - 3000:3000
    volumes:
      - ./data/config:/app/config
      - ./data/images:/app/public/images
      - ./data/icons:/app/public/icons
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /mnt/synology-nas/Files:/mnt/nas:ro
    networks:
      - proxy
      - adguard_dns_net
    dns:
      - 172.31.0.5
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.homepage.entrypoints=http"
      - "traefik.http.routers.homepage.rule=Host(`homepage.local.willkimble.net`)"
      - "traefik.http.middlewares.homepage-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.homepage.middlewares=homepage-https-redirect"
      - "traefik.http.routers.homepage-secure.entrypoints=https"
      - "traefik.http.routers.homepage-secure.rule=Host(`homepage.local.willkimble.net`)"
      - "traefik.http.routers.homepage-secure.tls=true"
      - "traefik.http.routers.homepage-secure.service=homepage"
      - "traefik.http.services.homepage.loadbalancer.server.port=3000"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.homepage-secure.middlewares=authelia@docker"
#################################################################
networks:
  proxy:
    external: true
  adguard_dns_net:
    external: true

