name: adguard
services:
#################################################################
  adguard:
    container_name: adguard
    image: adguard/adguardhome
    depends_on: [unbound]
    volumes:
      - ./data/adguard/work:/opt/adguardhome/work
      - ./data/adguard/conf:/opt/adguardhome/conf
    ports:
      # Plain DNS
      - 8000:80
      - 53:53/tcp
      - 53:53/udp
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    networks:
      proxy:
      dns_net:
        ipv4_address: ${ADGUARD_IP}
    env_file:
      - .env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.adguard.entrypoints=http"
      - "traefik.http.routers.adguard.rule=Host(`adguard.local.willkimble.net`)"
      - "traefik.http.middlewares.adguard-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.adguard.middlewares=adguard-https-redirect"
      - "traefik.http.routers.adguard-secure.entrypoints=https"
      - "traefik.http.routers.adguard-secure.rule=Host(`adguard.local.willkimble.net`)"
      - "traefik.http.routers.adguard-secure.tls=true"
      #- "traefik.http.routers.adguard-secure.tls.certresolver=http"
      - "traefik.http.routers.adguard-secure.service=adguard"
      - "traefik.http.services.adguard.loadbalancer.server.port=80"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.adguard-secure.middlewares=authelia@docker"
#################################################################
  unbound:
    container_name: unbound
    image: mvance/unbound:latest
    networks:
      dns_net:
        ipv4_address: ${UNBOUND_IP}
    env_file:
      - .env
    volumes:
      - ./data/unbound:/opt/unbound/etc/unbound
    expose:
      - 5053
    healthcheck:
      disable: true
    restart: unless-stopped
#################################################################
networks:
  proxy:
    external: true
  dns_net:
    driver: bridge
    ipam:
      config:
      - subnet: 172.31.0.0/24
