services:
#################################################################
  retrom:
    image: ghcr.io/jmberesford/retrom-service:latest
    container_name: retrom
#    ports:
#      - 5101:5101
    volumes:
      - ./data/config/:/config/ # directory containing your config file
      - /mnt/unraid-nas/data/media/games:/library
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      proxy:
      default:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.retrom.entrypoints=http"
      - "traefik.http.routers.retrom.rule=Host(`games.local.willkimble.net`)"
      - "traefik.http.middlewares.retrom-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.retrom.middlewares=retrom-https-redirect"
      - "traefik.http.routers.retrom-secure.entrypoints=https"
      - "traefik.http.routers.retrom-secure.rule=Host(`games.local.willkimble.net`)"
      - "traefik.http.routers.retrom-secure.tls=true"
      - "traefik.http.routers.retrom-secure.service=retrom"
      - "traefik.http.services.retrom.loadbalancer.server.port=3000"
      - "traefik.docker.network=proxy"
      - "com.centurylinklabs.watchtower.enable=true"
      - "traefik.http.routers.gameyfin-secure.middlewares=authelia@docker"
  retrom-db:
    container_name: retrom-db
    hostname: retrom-db # this should match the db_url in your config file
    image: postgres:16
    networks:
      default:
    restart: unless-stopped
    volumes:
      # to store the DB data on the host, change this path to any directory you like
      - ./data/postgres/:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: steve # db user, used to connect to the db, should match the db_user in your config file
      POSTGRES_PASSWORD: G9SA8WariY7Tp3h5oVbbQl6UQ8hcxL # db password for above user, should match the db_password in your config file
      POSTGRES_DB: retrom # db name, should match the db_name in your config file
#################################################################
networks:
  default:
  proxy:
    external: true
