services:
#################################################################
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    #image: lscr.io/linuxserver/jellyfin:10.8.10-1-ls220 #works for YT image extraction
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - JELLYFIN_PublishedServerUrl=jellyfin.local.willkimble.net #optional
    volumes:
      - ./data/config:/config
      - /mnt/unraid-nas/data/media/tv:/data/tv
      - /mnt/unraid-nas/data/media/movies:/data/movies
      - /mnt/unraid-nas/data/media/commentary:/data/commentary
      - /mnt/unraid-nas/data/media/youtube:/data/youtube
    ports:
      - 8096:8096
    group_add:
      - "105" # This is the "render" host group id
    devices:
      - /dev/dri:/dev/dri
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      proxy:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jellyfin.entrypoints=http"
      - "traefik.http.routers.jellyfin.rule=Host(`jellyfin.local.willkimble.net`)"
      - "traefik.http.middlewares.jellyfin-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.jellyfin.middlewares=jellyfin-https-redirect"
      - "traefik.http.routers.jellyfin-secure.entrypoints=https"
      - "traefik.http.routers.jellyfin-secure.rule=Host(`jellyfin.local.willkimble.net`)"
      - "traefik.http.routers.jellyfin-secure.tls=true"
      - "traefik.http.routers.jellyfin-secure.service=jellyfin"
      - "traefik.http.services.jellyfin.loadbalancer.server.port=8096"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.jellyfin-secure-middlewares=authelia@docker"
#################################################################
networks:
  proxy:
    external: true
