services:
#################################################################
  restarter:
#    image: docker:cli
    image: docker:20.10-cli #Temp fix
    container_name: qbittorrent_lt-restarter
    volumes: ["/var/run/docker.sock:/var/run/docker.sock"]
    command: ["/bin/sh", "-c", "while true; do sleep 86400; docker restart gluetun_lt qbittorrent_lt qbittorrent_lt-natmap; done"]
#    command: ["/bin/sh", "-c", "while true; do sleep 60; docker restart gluetun_lt qbittorrent_lt qbittorrent_lt-natmap; done"] #For testing
    restart: unless-stopped
#################################################################
  qbittorrent_lt-gluetun:
    #image: ghcr.io/qdm12/gluetun:v3.32 #Working
    image: ghcr.io/qdm12/gluetun:v3.39
    container_name: gluetun_lt
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    volumes:
      - ./data/gluetun:/gluetun
    environment:
      ## ProtonVPN Wireguard
      # See https://github.com/qdm12/gluetun/wiki
      - VPN_SERVICE_PROVIDER=custom
      - VPN_TYPE=wireguard
      - WIREGUARD_ENDPOINT_IP=${VPN_ENDPOINT_IP}
      - WIREGUARD_ENDPOINT_PORT=${VPN_ENDPOINT_PORT}
      - WIREGUARD_PUBLIC_KEY=${WIREGUARD_PUBLIC_KEY}
      - WIREGUARD_PRIVATE_KEY=${WIREGUARD_PRIVATE_KEY}
      - WIREGUARD_ADDRESSES=${WIREGUARD_ADDRESSES}
      - TZ=Etc/UTC
      - UPDATER_PERIOD=
      - UPDATER_VPN_SERVICE_PROVIDERS=
    env_file:
      - .env
    expose:
      - 8080/tcp # qBittorrent-lt
    security_opt:
      - no-new-privileges:true
    networks:
      proxy:
        ipv4_address: ${GLUETUN_IP}
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      ### qBittorrent Longterm ###
      - "traefik.http.routers.qbittorrent_lt.entrypoints=http"
      - "traefik.http.routers.qbittorrent_lt.rule=Host(`qbittorrent-lt.local.willkimble.net`)"
      - "traefik.http.routers.qbittorrent_lt.middlewares=qbittorrent-https-redirect"
      - "traefik.http.routers.qbittorrent_lt-secure.entrypoints=https"
      - "traefik.http.routers.qbittorrent_lt-secure.rule=Host(`qbittorrent-lt.local.willkimble.net`)"
      - "traefik.http.routers.qbittorrent_lt-secure.tls=true"
      - "traefik.http.routers.qbittorrent_lt-secure.service=qbittorrent_lt"
      - "traefik.http.services.qbittorrent_lt.loadbalancer.server.port=8080"
#################################################################
  qbittorrent_lt:
    # https://docs.linuxserver.io/images/docker-qbittorrent
    image: linuxserver/qbittorrent:5.0.1-libtorrentv1
    container_name: qbittorrent_lt
    restart: unless-stopped
    volumes:
      - ./data/qbittorrent:/config
      - /mnt/unraid-nas/data/torrents:/data/torrents
      - /mnt/unraid-nas/data/media/elearning:/elearning           #E-learning
      - /mnt/unraid-nas/data/media/games/switch:/switch           #Games - Switch
      - /mnt/unraid-nas/data/media/games/pc:/pc                   #Games - PC
      - /mnt/unraid-nas/data/media/games/vr:/vr                   #Games - VR
      - /mnt/unraid-nas/data/torrents/music:/music                #Music
      - /mnt/unraid-nas/data/media/books/ebooks:/ebooks           #eBooks
      - /mnt/unraid-nas/data/media/books/audiobooks:/audiobooks   #Audiobooks
      - /mnt/unraid-nas/data/torrents/longterm:/longterm          #Long Term/Temp 
    environment:
      - TZ=Etc/UTC
      - WEBUI_PORT=8080
      - PUID=99
      - PGID=100
    network_mode: "service:qbittorrent_lt-gluetun"
    depends_on:
      qbittorrent_lt-gluetun:
        condition: service_healthy
    security_opt:
      - no-new-privileges:true
#################################################################
  qbittorrent_lt-natmap:
    # https://github.com/soxfor/qbittorrent-natmap
    image: ghcr.io/soxfor/qbittorrent-natmap:latest
    container_name: qbittorrent_lt-natmap
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - TZ=Etc/UTC
      # QBit Settings
      - QBITTORRENT_SERVER=${QBITTORRENT_SERVER}
      - QBITTORRENT_PORT=${QBITTORRENT_PORT}
      - QBITTORRENT_USER=${QBITTORRENT_USER}
      - QBITTORRENT_PASS=${QBITTORRENT_PASS}
      # VPN Settings 
      - VPN_GATEWAY=
      - VPN_CT_NAME=gluetun_lt
      - VPN_IF_NAME=tun0
      - CHECK_INTERVAL=200
      - NAT_LEASE_LIFETIME=200
    env_file:
      - .env
    network_mode: "service:qbittorrent_lt-gluetun"
    depends_on:
      qbittorrent_lt:
        condition: service_started
      qbittorrent_lt-gluetun:
        condition: service_healthy
    security_opt:
      - no-new-privileges:true
#################################################################
networks:
  proxy:
    external: true
